Chart.defaults.global.defaultFontFamily="'LM Mono 10',Consolas";
Chart.defaults.global.defaultFontSize=11*96/72;
Papa.parse
(
    "/notebook/misc/190220chartjs1.csv",
    {
        download:true,
        complete:function(results)
        {
            new Chart
            (
                document.getElementById("Figure1"),
                {
                    type:"line",
                    data:
                    {
                        labels:results.data[0],
                        datasets:
                        [
                            {
                                label:"Quadratic",
                                data:results.data[1],
                                borderColor:"Blue",
                                backgroundColor:"Blue",
                                fill:false
                            },
                            {
                                label:"Exponential",
                                data:results.data[2],
                                borderColor:"Red",
                                backgroundColor:"Red",
                                fill:false
                            }
                        ]
                    },
                    options:
                    {
                        responsive:false
                    }
                }
            );
        }
    }
);
Papa.parse
(
    "/notebook/misc/190220chartjs2.csv",
    {
        download:true,
        header:true,
        complete:function(results)
        {
            results.data1=[];
            results.data2=[];
            for(i=0;i<results.data.length-1;i++)
            {
                results.data1[i]={};
                results.data1[i].x=results.data[i].x;
                results.data1[i].y=results.data[i].y1;
                results.data2[i]={};
                results.data2[i].x=results.data[i].x;
                results.data2[i].y=results.data[i].y2;
            }
            new Chart
            (
                document.getElementById("Figure2"),
                {
                    type:"scatter",
                    data:
                    {
                        datasets:
                        [
                            {
                                label:"Quadratic",
                                data:results.data1,
                                borderColor:"Blue",
                                backgroundColor:"Blue",
                                fill:false,
                                showLine:true
                            },
                            {
                                label:"Exponential",
                                data:results.data2,
                                borderColor:"Red",
                                backgroundColor:"Red",
                                fill:false,
                                showLine:true
                            }
                        ]
                    },
                    options:
                    {
                        responsive:false
                    }
                }
            );
        }
    }
);
Papa.parse
(
    "/notebook/misc/190220chartjs3.csv",
    {
        download:true,
        header:true,
        complete:function(results)
        {
            results.data1=[];
            results.data2=[];
            for(i=0;i<results.data.length-1;i++)
            {
                results.data1[i]={};
                results.data1[i].x=results.data[i].x1;
                results.data1[i].y=results.data[i].y1;
                results.data2[i]={};
                results.data2[i].x=results.data[i].x2;
                results.data2[i].y=results.data[i].y2;
            }
            new Chart
            (
                document.getElementById("Figure3"),
                {
                    type:"scatter",
                    data:
                    {
                        datasets:
                        [
                            {
                                label:"call streaminit(1)",
                                data:results.data1,
                                borderColor:"Blue",
                                backgroundColor:"Blue",
                                fill:false
                            },
                            {
                                label:"call streaminit(2)",
                                data:results.data2,
                                borderColor:"Red",
                                backgroundColor:"Red",
                                fill:false
                            }
                        ]
                    },
                    options:
                    {
                        responsive:false
                    }
                }
            );
        }
    }
);
Papa.parse
(
    "/notebook/misc/190220chartjs4.csv",
    {
        download:true,
        complete:function(results)
        {
            new Chart
            (
                document.getElementById("Figure4"),
                {
                    type:"bar",
                    data:
                    {
                        labels:results.data[0],
                        datasets:
                        [
                            {
                                label:"call streaminit(1)",
                                data:results.data[1],
                                borderColor:"Blue",
                                backgroundColor:"Blue",
                                fill:false
                            },
                            {
                                type:"line",
                                label:'rand("normal",0,1)',
                                data:results.data[2],
                                borderColor:"Red",
                                backgroundColor:"Red",
                                fill:false,
                                pointRadius:0
                            }
                        ]
                    },
                    options:
                    {
                        responsive:false,
                        yAxes:[{ticks:{beginAtZero:true}}]
                    }
                }
            );
        }
    }
);
Papa.parse
(
    "/notebook/misc/190220chartjs5.csv",
    {
        download:true,
        complete:function(results)
        {
            new Chart
            (
                document.getElementById("Figure5"),
                {
                    type:"horizontalBar",
                    data:
                    {
                        labels:results.data[0],
                        datasets:
                        [
                            {
                                label:"call streaminit(1)",
                                data:results.data[1],
                                borderColor:"Blue",
                                backgroundColor:"Blue",
                                fill:false
                            },
                            {
                                label:"call streaminit(2)",
                                data:results.data[2],
                                borderColor:"Red",
                                backgroundColor:"Red",
                                fill:false
                            }
                        ]
                    },
                    options:
                    {
                        responsive:false,
                        xAxes:[{ticks:{beginAtZero:true}}]
                    }
                }
            );
        }
    }
);
Papa.parse
(
    "/notebook/misc/190226chartjs1.csv",
    {
        download:true,
        header:true,
        complete:function(results)
        {
            results.data.splice(results.data.length-1,results.data.length-1);
            new Chart
            (
                document.getElementById("Figure6"),
                {
                    type:"scatter",
                    data:
                    {
                        datasets:
                        [
                            {
                                label:"ICS_ALL",
                                data:results.data,
                                borderColor:"Blue",
                                backgroundColor:"Blue",
                                fill:false,
                                showLine:true,
                                lineTension:0,
                                pointRadius:0
                            }
                        ]
                    },
                    options:
                    {
                        responsive:false
                    }
                }
            );
        }
    }
);
Papa.parse
(
    "/notebook/misc/190226chartjs2.csv",
    {
        download:true,
        header:true,
        complete:function(results)
        {
            results.data.splice(results.data.length-1,results.data.length-1);
            new Chart
            (
                document.getElementById("Figure7"),
                {
                    type:"scatter",
                    data:
                    {
                        datasets:
                        [
                            {
                                label:"FEDFUNDS",
                                data:results.data,
                                borderColor:"Blue",
                                backgroundColor:"Blue",
                                fill:false,
                                showLine:true,
                                lineTension:0,
                                pointRadius:0
                            }
                        ]
                    },
                    options:
                    {
                        responsive:false
                    }
                }
            );
        }
    }
);
Papa.parse
(
    "/notebook/misc/190226chartjs3.csv",
    {
        download:true,
        header:true,
        complete:function(results)
        {
            results.data.splice(results.data.length-1,results.data.length-1);
            new Chart
            (
                document.getElementById("Figure8"),
                {
                    type:"scatter",
                    data:
                    {
                        datasets:
                        [
                            {
                                label:"cay",
                                data:results.data,
                                borderColor:"Blue",
                                backgroundColor:"Blue",
                                fill:false,
                                showLine:true,
                                lineTension:0,
                                pointRadius:0
                            }
                        ]
                    },
                    options:
                    {
                        responsive:false
                    }
                }
            );
        }
    }
);
Papa.parse
(
    "/notebook/misc/190226chartjs4.csv",
    {
        download:true,
        header:true,
        complete:function(results)
        {
            results.data1=[];
            results.data2=[];
            results.data3=[];
            results.data4=[];
            results.data5=[];
            results.data6=[];
            for(i=0;i<results.data.length-1;i++)
            {
                results.data1[i]={};
                results.data1[i].x=results.data[i].x;
                results.data1[i].y=results.data[i].y1;
                results.data2[i]={};
                results.data2[i].x=results.data[i].x;
                results.data2[i].y=results.data[i].y2;
                results.data3[i]={};
                results.data3[i].x=results.data[i].x;
                results.data3[i].y=results.data[i].y3;
                results.data4[i]={};
                results.data4[i].x=results.data[i].x;
                results.data4[i].y=results.data[i].y4;
                results.data5[i]={};
                results.data5[i].x=results.data[i].x;
                results.data5[i].y=results.data[i].y5;
                results.data6[i]={};
                results.data6[i].x=results.data[i].x;
                results.data6[i].y=results.data[i].y6;
            }
            new Chart
            (
                document.getElementById("Figure9"),
                {
                    type:"scatter",
                    data:
                    {
                        datasets:
                        [
                            {
                                label:"Mkt-RF",
                                data:results.data1,
                                borderColor:"Blue",
                                backgroundColor:"Blue",
                                fill:false,
                                showLine:true,
                                lineTension:0,
                                pointRadius:0
                            },{
                                label:"SMB",
                                data:results.data2,
                                borderColor:"Red",
                                backgroundColor:"Red",
                                fill:false,
                                showLine:true,
                                lineTension:0,
                                pointRadius:0
                            },{
                                label:"HML",
                                data:results.data3,
                                borderColor:"Lime",
                                backgroundColor:"Lime",
                                fill:false,
                                showLine:true,
                                lineTension:0,
                                pointRadius:0
                            },{
                                label:"RMW",
                                data:results.data4,
                                borderColor:"Fuchsia",
                                backgroundColor:"Fuchsia",
                                fill:false,
                                showLine:true,
                                lineTension:0,
                                pointRadius:0
                            },{
                                label:"CMA",
                                data:results.data5,
                                borderColor:"Aqua",
                                backgroundColor:"Aqua",
                                fill:false,
                                showLine:true,
                                lineTension:0,
                                pointRadius:0
                            },{
                                label:"RF",
                                data:results.data6,
                                borderColor:"Yellow",
                                backgroundColor:"Yellow",
                                fill:false,
                                showLine:true,
                                lineTension:0,
                                pointRadius:0
                            }
                        ]
                    },
                    options:
                    {
                        responsive:false
                    }
                }
            );
        }
    }
);
